expname = "lego2"
basedir = "./result/"

[dataset]
    datadir = "./data/nerf_synthetic/lego"
    white_bkgd = true

[training]
  lr_decay = 250000
  N_rand = 256
  N_iters = 1000000
  netchunk = 196608
  precrop_iters = 1500
  precrop_frac = 0.5
  fewshot = 4
  train_scene = [26, 86, 2, 55]

  i_testset = 10000
  # ckpt = "./logs/lego_naive/ckpt"
 
[rendering]
  use_viewdirs = true
  N_samples = 64
  N_importance = 128
  near = 2.0
  far = 6.0

[entropy_loss]
  use = true
  N_entropy = 256
  entropy_ray_zvals_lambda = 1e-3
  entropy_end_iter = -1

[info_loss]
  use = false
  sampling_method = 'near_pose'
  near_c2w_type = 'rot_from_origin'
  near_c2w_rot = 3.0
  near_c2w_trans = 0.05
  pixel_range = 16
  info_lambda = 0.5
  activation = 'norm'
  reduce_step_size = 5000
  reduce_step_rate = 0.5
  info_end_iter = -1
